export const S3_ENV_KEYS = {
  BUCKET: 'S3_BUCKET',
  REGION: 'S3_REGION',
  ENDPOINT: 'S3_ENDPOINT',
  ACCESS_KEY: 'S3_ACCESS_KEY',
  SECRET_KEY: 'S3_SECRET_KEY',
  FORCE_PATH_STYLE: 'S3_FORCE_PATH_STYLE',
  PUBLIC_BASE_URL: 'S3_PUBLIC_BASE_URL',
} as const;
